# Generated by Django 5.0.4 on 2024-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('Expense', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Payment', models.CharField(max_length=50)),
            ],
        ),
    ]
